# Generated by Django 3.1.3 on 2022-07-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmedico', models.IntegerField()),
                ('idconsultorio', models.IntegerField()),
                ('idturno', models.IntegerField()),
                ('cupos', models.IntegerField()),
                ('minutos', models.TimeField()),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'programacion',
                'managed': True,
            },
        ),
    ]
