# Generated by Django 3.1.3 on 2022-07-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='fechaProgramada',
            field=models.DateField(null=True),
        ),
    ]
