# Generated by Django 3.1.3 on 2022-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprogramacion', models.IntegerField()),
                ('historia', models.IntegerField()),
                ('fechacita', models.DateField()),
                ('orden', models.IntegerField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='R', max_length=1)),
            ],
            options={
                'db_table': 'citas',
                'managed': True,
            },
        ),
    ]
